import type { Metadata } from "next";
import "@/app/globals.css";
import { poppins } from "@/app/ui/fonts";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
        <html lang="en">
          <body
            className={`${poppins.variable} antialiased`}
          >
            {children}
          </body>
        </html>
    </SessionProvider>
  );
}
